#include"Arduino.h"
#include"Morse.h"
Morse morse(13);
char c="";
void setup() {
  Serial.begin(9600);//设置频率
}

void loop() {
   while (Serial.available() > 0){
    c=Serial.read();
       if(c=='a')
       {morse.dot();
        morse.dash();}
        if(c=='b')
       {morse.dash();
        morse.dot();
        morse.dot();
        morse.dot();}
        if(c=='c')
       {morse.dash();
        morse.dot();
        morse.dash();
        morse.dot();}
        if(c=='d')
       {morse.dash();
        morse.dot();
        morse.dot();}
        if(c=='e')
       {morse.dot();}
        if(c=='f')
       {morse.dot();
        morse.dot();
        morse.dash();
        morse.dot();}
        if(c=='g')
       {morse.dash();
        morse.dash();
        morse.dot();}
        if(c=='h')
       {morse.dot();
        morse.dot();
        morse.dot();
        morse.dot();}
        if(c=='i')
       {morse.dot();
        morse.dot();}
        if(c=='j')
       {morse.dot();
        morse.dash();
        morse.dash();
        morse.dash();}
        if(c=='k')
       {morse.dash();
        morse.dot();
        morse.dash();}
        if(c=='l')
       {morse.dot();
        morse.dash();
        morse.dot();
        morse.dot();}
        if(c=='m')
       {morse.dash();
        morse.dash();}
        if(c=='n')
       {morse.dash();
        morse.dot();}
        if(c=='o')
       {morse.dash();
        morse.dash();
        morse.dash();}
        if(c=='p')
       {morse.dot();
        morse.dash();
        morse.dash();
        morse.dot();}
        if(c=='q')
       {morse.dash();
        morse.dash();
        morse.dot();
        morse.dash();}
        if(c=='r')
       {morse.dot();
        morse.dash();
        morse.dot();}
        if(c=='s')
       {morse.dot();
        morse.dot();
        morse.dot();}
        if(c=='t')
       {morse.dash();}
        if(c=='u')
       {morse.dot();
        morse.dot();
        morse.dash();}
        if(c=='v')
       {morse.dot();
        morse.dot();
        morse.dot();
        morse.dash();}
        if(c=='w')
       {morse.dot();
        morse.dash();
        morse.dash();}
        if(c=='x')
       {morse.dash();
        morse.dot();
        morse.dot();
        morse.dash();}
        if(c=='y')
       {morse.dash();
        morse.dot();
        morse.dash();
        morse.dash();}
        if(c=='z')
       {morse.dash();
        morse.dash();
        morse.dot();
        morse.dot();}
}
}
